### ISSUE TITLE
Test framework for tools

### ISSUE THREAD

**Issue by dazuma** [dazuma/toys#13]
There should be facilities to make it easier to test tools. Some general ideas:
* Try to avoid requiring a specific test framework (e.g. minitest vs. rspec)
* Need a standard place to put tests, maybe a `.toys/test` directory
* Convenience tool to load toys files, run tests, and capture results
* Ways to mock out subprocesses and other side effects

**Comment by AlexWayfer** [comment]
> dazuma closed this 9 hours ago

Why? Is it implemented?

**Comment by dazuma** [comment]
> > dazuma closed this 9 hours ago
> 
> Why? Is it implemented?

Yes, in #123. It's still a bit experimental, and there are a bunch of tools (like stubbing `exec` calls) that still need to be implemented, but I think we need a bit of experience working with it before we can finalize what those interfaces should look like.
