### ISSUE TITLE
[Question] "Shared" flags via mixins — possible?

### ISSUE THREAD

**Issue by recup** [dazuma/toys#3]
Hi, I like toys so far, thanks for building it. :)  I have a question, though.

I have a couple of tools which should offer a `--app` flag (think Heroku toolbelt). The functionality tied to this flag is identical for all tools (flag is used to load a particular set of ENV vars), so I thought maybe I can write a mixins class or a template class. But it seems to me that templates can only define arguments, is that correct?

I'd appreciate some examples on how to write code for sharing flags and flag-related functionality.  Thanks in advance!

**Comment by dazuma** [comment]
Probably the easiest way is to define a mixin with an `on_include` block. Here's an example:

```ruby
# .toys.rb
mixin "app-related" do
  on_include do
    # You can add flags or any other directives here. They effectively get
    # added to the tool at the place where you include the mixin.
    flag :app, "--app=APP", desc: "The app name"
  end
  # The usual purpose of mixins is to define a bunch of helper methods,
  # just like modules in Ruby.
  def display_app
    puts "The app was #{app.inspect}"
  end
end

tool "my-tool" do
  include "app-related"
  def run
    display_app
  end
end
```

```sh
$ toys my-tool
The app was nil
$ toys my-tool --app=hello
The app was "hello"
$
```

It's also possible to use a template for this. Templates can basically generate arbitrary code—think of them as metaprogramming for Toys. But I'd consider mixins a cleaner technique for "adding common directives and code to a bunch of tools".

**Comment by recup** [comment]
Exactly what I was looking for. Once again, thank you very much. :)
