### ISSUE TITLE
Ability to exec tools with flags as Hash

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#33]
Hello!

Documentation of `exec_tool` is pretty insufficient, and I'm trying to use it blindly.

I see that it accepts the first argument as String or an Array of String-convertible elements which will be a command. And the second argument as some (unclear) spawn options.

And if I have a tool with `required_arg :name`, for example, I can call it like `exec_tool ['foo', 'Alex']`. But if I have a tool with `flag :name, '-n', '--name'` — I should probably call it like `exec_tool ['foo', '--name=Alex']`, but it'd be nice to have an ability to pass a Hash of known flags like `exec_tool ['foo', name: 'Alex']`.

**Comment by dazuma** [comment]
I expanded the documentation for the `:exec` mixin considerably in version 0.10.1 and later. (See https://dazuma.github.io/toys/gems/toys-core/latest/Toys/StandardMixins/Exec.html). Hope that helps a bit.

As for passing a hash of flags, I'm not sure I'm convinced it's a good idea. These are command line tools, and the arguments are meant to be given as command line arguments. (For example, some tools let you specify certain arguments more than once—how does that translate from a Hash?) Have you found other tools/libraries that call arbitrary command line executables by passing arguments as a hash (or dictionary, etc.)?

**Comment by AlexWayfer** [comment]
> As for passing a hash of flags, I'm not sure I'm convinced it's a good idea. These are command line tools, and the arguments are meant to be given as command line arguments. (For example, some tools let you specify certain arguments more than once—how does that translate from a Hash?)

OK, I got it, thanks.

> Have you found other tools/libraries that call arbitrary command line executables by passing arguments as a hash (or dictionary, etc.)?

I didn't find and don't remember.
