### ISSUE TITLE
[Question] How can I change the default logger verbosity?

### ISSUE THREAD

**Issue by recup** [dazuma/toys#4]
I'd love to set the default verbosity for a subtree of tools, how can I do that?

**Comment by dazuma** [comment]
Unfortunately there isn't a way (currently) to affect an entire subtree. It's likely this could be addressed by customizing the middleware stack, which is a feature area that seems useful but that I've been putting off designing (because of its complexity and because some of the semantics aren't really clear to me yet).

For now I suggest creating a mixin that affects the verbosity. Then you'd have to include that mixin for all the tools that it should apply to. Here's an example:

```ruby
mixin "more-verbose" do
  on_initialize do
    # Increase the verbosity by 1 before running the tool
    set(VERBOSITY, get(VERBOSITY) + 1)
  end
end

tool "foo" do
  include "more-verbose"
  def run
    logger.info "hello from foo"
  end

  tool "bar" do
    include "more-verbose"
    def run
      logger.info "hello from foo bar"
    end
  end
end

tool "unchanged" do
  def run
    logger.info "hello from unchanged"
  end
end
```

Example runs:

```sh
$ toys unchanged
$ toys unchanged -v
[2019-11-28 14:34:55  INFO]  hello from unchanged
$ toys foo
[2019-11-28 14:35:07  INFO]  hello from foo
$ toys foo -q
$ toys foo bar
[2019-11-28 14:35:31  INFO]  hello from foo bar
$
```

**Comment by recup** [comment]
Thanks!

> Unfortunately there isn't a way (currently) to affect an entire subtree.

Alright, I see. Good to know, but it's not a problem for me.

So far, I've only defined mixin modules — so far, they're not Toys-specific but general mixins, and I put them in their own folder.

Also, since I'm using [Toys directories](https://www.rubydoc.info/gems/toys/file/docs/guide.md#Toys_directories), I'm not using the `tool` keywords/blocks. That works well but how would I go about defining a `mixin` block outside of a tool file? Taking your In your README example …

```
(current directory)
|
+- .toys/
   |
   +- greet.rb   <-- defines "greet" (and subtools)
```

… where and how would I create a mixin which I could then use in any tool, like `greet` as well it's siblings?

Apologies if my questions may seem a bit basic but I'm learning over here. :)

**Comment by dazuma** [comment]
No apologies at all. You're already discussing some of the advanced features that I myself have used only once or twice.

Mixin blocks are "lexically scoped" in that they are visible to any subtool of the current tool (defined under the same toys directory). So if you define a `mixin` block inside `greet.rb`, it will be visible, recursively, to any subtool or descendant of `greet` (even when those are defined in different files under the same overall `.toys` directory)

To define a mixin visible to _all_ tools (including `greet` itself), add it to `.toys/.toys.rb` which defines the "toplevel" tool. (See [this section on "index files"](https://www.rubydoc.info/gems/toys/file/docs/guide.md#Index_files) in the user guide.)

**Comment by recup** [comment]
Thank you for the explanation — that was the missing bit that made the whole setup really click for me! 👍
