### ISSUE TITLE
Pass flags to `exec` inside tool

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#55]
Hello.

If I have a tool like:

```ruby
tool :rspec do
  def run
    exec 'rspec'
  end
end
```

can I somehow pass flags to `exec`? Without it's duplication in a tool itself.

For usage like:

```sh
toys rspec --format=doc
```

**Comment by dazuma** [comment]
You can disable Toys' argument parsing, and then pass the raw arguments to the program you're running. There's an example here: https://dazuma.github.io/toys/gems/toys/v0.10.4/file.guide.html#disabling-argument-parsing

**Comment by AlexWayfer** [comment]
> You can disable Toys' argument parsing, and then pass the raw arguments to the program you're running. There's an example here: https://dazuma.github.io/toys/gems/toys/v0.10.4/file.guide.html#disabling-argument-parsing

Thank you! I searched by "pass" ("passing") keyword and didn't find.
