### ISSUE TITLE
Strange `--help` of alias

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#59]
Hello.

I have the `s` alias for `server` tool with sub-tools, and `toys s --help` result looks weird:

![image](https://user-images.githubusercontent.com/6510020/89123897-8440ff80-d4db-11ea-86fd-ae973e53196c.png)

If I press Arrow Up key:

![image](https://user-images.githubusercontent.com/6510020/89123906-928f1b80-d4db-11ea-8ec6-4ace075bbc94.png)

Then I can't move anywhere else via Arrow or Page keys.

Gem with tools: https://github.com/AlexWayfer/flame_server_toys

**Comment by dazuma** [comment]
So the paging behavior is just the normal behavior of [less](https://man7.org/linux/man-pages/man1/less.1.html) when given a short input.

I agree about the content being not very useful, though. I'll see what I can do to improve it.

**Comment by AlexWayfer** [comment]
OK, thank you.
