### ISSUE TITLE
Setup CI for Pull requests

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#7]
Hello.

I see Circle CI config and badge, but I don't see any checks in my PR.

**Comment by dazuma** [comment]
Looks like there was a CircleCI setting that I missed. It should be fixed now. (It probably won't affect the existing open PR, but it should take effect for subsequent PRs.)

**Comment by AlexWayfer** [comment]
Yeah, it work for existing PR. Thank you.
