### ISSUE TITLE
can't find executable bundler for gem bundler

### ISSUE THREAD

**Issue by AlexWayfer** [dazuma/toys#96]
With such file:

```yaml
# .bundle/config

BUNDLE_PATH: "vendor"
```

Output is:

```
> toys s start
...
Traceback (most recent call last):
	2: from /home/alex/.rbenv/versions/2.7.1/bin/bundler:23:in `<main>'
	1: from /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable bundler for gem bundler (Gem::Exception)
...
```

The same with `bundle exec toys s start`.

Without using local copy of gems everything is OK.

**Comment by dazuma** [comment]
I'm not able to reproduce this one. I tried setting the bundle config, providing a Gemfile, and using this:

```ruby
# .toys.rb
tool "foo" do
  include :bundler, static: true
  def run
    puts "hi"
  end
end
```

It seemed to work fine.(It asked to install the bundle, and it did so in the `vendor/` directory, and then ran the tool.) I also tried without `static: true`.

Is this still happening for you? Can you provide any more reproduction information?

**Comment by AlexWayfer** [comment]
Sorry for late response, I faced again with this problem in CI.

So, the problem is when `path` for Bundler is redefined, locally or user-scope.

Reproduction:

1.  Create a `Gemfile` with a gem, in my example it's `clamp`:
    ```ruby
    # frozen_string_literal: true

    source 'https://rubygems.org'

    gem 'clamp'
    ```
2.  Create a `.toys.rb` file, it can be without tools:
    ```ruby
    # frozen_string_literal: true

    include :bundler, static: true
    ```
3.  Unisntall system-wide version of this gem:
    ```
    gem uninstall clamp
    ```
4.  Set custom Bundler path (with or without `--local`):
    ```
    bundle config --local set path 'vendor'
    ```
5.  Install Bundle:
    ```
    bundle install
    ```
6.  Now, the Bundle works and installed, but any `toys` call asking for installation:
    ```
    > toys --help
    Your bundle requires additional gems. Install? (Y/n)
    ```
